-- MySQL Script generated by MySQL Workbench
-- Thu Mar 30 10:22:15 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `polamap` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;


-- -----------------------------------------------------
-- Table `mydb`.`Rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Rol` (
  `idRol` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `descripcion` VARCHAR(45) NULL,
  PRIMARY KEY (`idRol`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Registro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Registro` (
  `idRegsitro` INT NOT NULL AUTO_INCREMENT,
  `Usuario` VARCHAR(45) NULL,
  `correo` VARCHAR(45) NULL,
  `contraseña` VARCHAR(45) NULL,
  `Rol_idRol` INT NOT NULL,
  PRIMARY KEY (`idRegsitro`),
  INDEX `fk_Registro_Rol1_idx` (`Rol_idRol` ASC) VISIBLE,
  CONSTRAINT `fk_Registro_Rol1`
    FOREIGN KEY (`Rol_idRol`)
    REFERENCES `mydb`.`Rol` (`idRol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`establecimientos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`establecimientos` (
  `idEstablecimientos` INT NOT NULL AUTO_INCREMENT,
  `oferta` VARCHAR(45) NULL,
  `nombreEstablecimeinto` VARCHAR(45) NULL,
  `urlImgEstablecimiento` VARCHAR(100) NULL,
  `descripcionestablecimiento` VARCHAR(45) NULL,
  PRIMARY KEY (`idEstablecimientos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`promocion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`promocion` (
  `idPromocion` INT NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `tipo` INT NULL,
  PRIMARY KEY (`idPromocion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`boletas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`boletas` (
  `idboletas` INT NOT NULL AUTO_INCREMENT,
  `nombreBoletas` VARCHAR(45) NULL,
  `cantidad` INT NULL,
  `precio` FLOAT NULL,
  `fechaBoleta` DATE NULL,
  `descripcionBoleta` VARCHAR(100) NULL,
  `urlImgBoleta` VARCHAR(100) NULL,
  `establecimientos_idEstablecimientos` INT NOT NULL,
  `promocion_idPromocion` INT NOT NULL,
  PRIMARY KEY (`idboletas`, `establecimientos_idEstablecimientos`),
  INDEX `fk_boletas_establecimientos1_idx` (`establecimientos_idEstablecimientos` ASC) VISIBLE,
  INDEX `fk_boletas_promocion1_idx` (`promocion_idPromocion` ASC) VISIBLE,
  CONSTRAINT `fk_boletas_establecimientos1`
    FOREIGN KEY (`establecimientos_idEstablecimientos`)
    REFERENCES `mydb`.`establecimientos` (`idEstablecimientos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_boletas_promocion1`
    FOREIGN KEY (`promocion_idPromocion`)
    REFERENCES `mydb`.`promocion` (`idPromocion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Compra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Compra` (
  `idCompra` INT NOT NULL,
  `PrecioTotal` DECIMAL NULL,
  `Cliente_idCliente` INT NOT NULL,
  `cedula` INT NULL,
  `Registro_idRegsitro` INT NOT NULL,
  PRIMARY KEY (`idCompra`, `Registro_idRegsitro`),
  INDEX `fk_Compra_Registro1_idx` (`Registro_idRegsitro` ASC) VISIBLE,
  CONSTRAINT `fk_Compra_Registro1`
    FOREIGN KEY (`Registro_idRegsitro`)
    REFERENCES `mydb`.`Registro` (`idRegsitro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Compra_boletas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Compra_boletas` (
  `Compra_idcompra` INT NOT NULL,
  `boletas_idboletas` INT NOT NULL,
  `boletas_establecimientos_idEstablecimientos` INT NOT NULL,
  `cantidad_boletas` INT NULL,
  PRIMARY KEY (`Compra_idcompra`, `boletas_idboletas`, `boletas_establecimientos_idEstablecimientos`),
  INDEX `fk_Compra_has_boletas_boletas1_idx` (`boletas_idboletas` ASC, `boletas_establecimientos_idEstablecimientos` ASC) VISIBLE,
  INDEX `fk_Compra_has_boletas_Compra1_idx` (`Compra_idcompra` ASC) VISIBLE,
  CONSTRAINT `fk_Compra_has_boletas_Compra1`
    FOREIGN KEY (`Compra_idcompra`)
    REFERENCES `mydb`.`Compra` (`idCompra`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Compra_has_boletas_boletas1`
    FOREIGN KEY (`boletas_idboletas` , `boletas_establecimientos_idEstablecimientos`)
    REFERENCES `mydb`.`boletas` (`idboletas` , `establecimientos_idEstablecimientos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `mydb` ;

-- -----------------------------------------------------
-- Placeholder table for view `mydb`.`view1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`view1` (`id` INT);

-- -----------------------------------------------------
--  routine1
-- -----------------------------------------------------

DELIMITER $$
USE `mydb`$$
$$

DELIMITER ;

-- -----------------------------------------------------
-- View `mydb`.`view1`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`view1`;
USE `mydb`;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
